### ISSUE TITLE
fix parity chunk with more than 4 corrupt segments

### ISSUE THREAD

**Issue by anarchy9388** [anarchy9388/chunky_monkey#8]
Meanwhile , I think we can add one more function to the chunky_monkey
about how to fix the parity chunk when it have more than 4 corrupted segments.
for example, if the parity chunk got 5 or 6 segments corrupted, so we can read the one or two segment data from the encoded chunk's local zone and do xor for it manually and dd it back to the parity chunk, so the parity chunk will get enough segment(12) to recover (edited) 

Example script from another case attached.

[fix_parity_chunk_bad_segment.py.txt](https://github.com/anarchy9388/chunky_monkey/files/3215109/fix_parity_chunk_bad_segment.py.txt)

**Comment by MarkHe1222** [comment]
Yes, that's what I'm talking about.
Let's put it into vesrsion 0.2
